import { createHash } from 'node:crypto'
import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import type { Aoi, Params } from '../shared/types.js'

/**
 * Reuses a region's results when nothing that could change them has changed.
 *
 * Regions are independent by construction -- each is rasterised, searched and refined on its own,
 * and only pooled at the end -- so re-running one because another was edited is pure waste. Adding
 * a small area used to cost a full re-run of every other, which for a 141 km2 neighbour is ten
 * minutes.
 *
 * A cache file is named for the region's *identity* -- the rectangles it covers -- and records what
 * it was generated with inside: a fingerprint of the pipeline and shared source, and the parameters
 * by value. That split is what makes a stale entry usable. Keying on the fingerprint instead, which
 * is what this used to do, meant a region whose code had changed could not even be found, so the
 * only choice on offer was recompute-or-nothing. Now a caller can knowingly serve last week's
 * Eberswalde while recomputing the small area it actually edited -- see `current` on a hit, which is
 * the caller's cue to say so rather than to pretend the dataset is uniform.
 *
 * Two files are excluded from the fingerprint. Tests cannot affect output. And params.ts holds only
 * data -- the parameters and the list of areas -- both of which are compared by value, so hashing
 * it as source would mean adding one area invalidated every other, which is exactly what this
 * exists to avoid.
 */

const DATA_ONLY = new Set(['params.ts'])

const CACHE_DIR = new URL('../../data/cache/', import.meta.url).pathname
const SOURCE_DIRS = ['../pipeline/', '../shared/']

let fingerprint: string | null = null

async function sourceFingerprint(): Promise<string> {
  if (fingerprint) return fingerprint
  const hash = createHash('sha1')
  for (const dir of SOURCE_DIRS) {
    const path = new URL(dir, import.meta.url).pathname
    for (const name of (await readdir(path)).sort()) {
      if (!name.endsWith('.ts') || name.endsWith('.test.ts') || DATA_ONLY.has(name)) continue
      hash.update(name)
      hash.update(await readFile(join(path, name)))
    }
  }
  fingerprint = hash.digest('hex').slice(0, 12)
  return fingerprint
}

/** Which region this is, by the ground it covers. Stable across every change to code or tuning. */
export function regionId(aois: Aoi[]): string {
  return createHash('sha1').update(JSON.stringify(aois)).digest('hex').slice(0, 16)
}

interface Envelope<T> {
  fingerprint: string
  /** Serialised rather than structured, since it is only ever compared for equality. */
  params: string
  generatedAt: string
  value: T
}

export interface CacheHit<T> {
  value: T
  /** Whether it was generated by this code with these parameters. False means usable but stale. */
  current: boolean
  generatedAt: string
}

const pathFor = (id: string) => join(CACHE_DIR, `region_${id}.json`)

export async function readRegion<T>(aois: Aoi[], p: Params): Promise<CacheHit<T> | null> {
  let held: Envelope<T>
  try {
    held = JSON.parse(await readFile(pathFor(regionId(aois)), 'utf8')) as Envelope<T>
  } catch {
    return null
  }
  // A file from before the envelope existed, or a truncated one. Either way there is no way to know
  // what it was generated with, and guessing is worse than recomputing.
  if (!held || typeof held.fingerprint !== 'string') return null
  return {
    value: held.value,
    current: held.fingerprint === (await sourceFingerprint()) && held.params === JSON.stringify(p),
    generatedAt: held.generatedAt,
  }
}

export async function writeRegion<T>(aois: Aoi[], p: Params, value: T): Promise<number> {
  await mkdir(CACHE_DIR, { recursive: true })
  const held: Envelope<T> = {
    fingerprint: await sourceFingerprint(),
    params: JSON.stringify(p),
    generatedAt: new Date().toISOString(),
    value,
  }
  const text = JSON.stringify(held)
  await writeFile(pathFor(regionId(aois)), text)
  return text.length
}
